# mkdir -p grafana_data prometheus_data tempo-data && chown -R 472:472 grafana_data && chown -R 65534:65534 prometheus_data && chown -R 10001:10001 tempo-data
services:
  kong-database:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: kong-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-kong}
      - POSTGRES_DB=${POSTGRES_DB:-kong}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-kong}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong:
    depends_on:
      - kong-database
    image: kong:${KONG_VERSION:-latest}
    container_name: kong
    restart: always
    environment:
      - TZ=${TZ:-Asia/Bangkok}
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_PG_HOST:-kong-database}
      - KONG_PG_DATABASE=${POSTGRES_DB:-kong}
      - KONG_PG_USER=${POSTGRES_USER:-kong}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD:-kong}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN:-127.0.0.1:8001}
      - KONG_ADMIN_GUI_LISTEN=${KONG_ADMIN_GUI_LISTEN:-127.0.0.1:8002}
      - KONG_ADMIN_GUI_API_URL=${KONG_ADMIN_GUI_API_URL:-http://127.0.0.1:8001}
      - KONG_PROXY_LISTEN=${KONG_PROXY_LISTEN:-0.0.0.0:8000, 0.0.0.0:8443 ssl http2}
      - KONG_NGINX_HTTP_RESOLVER=${KONG_NGINX_HTTP_RESOLVER:-8.8.8.8}
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_REAL_IP_HEADER=Cf-Connecting-Ip
      - KONG_TRACING_INSTRUMENTATIONS=all
      - KONG_TRACING_SAMPLING_RATE=1.0
      - KONG_LOG_LEVEL=debug
    ports:
      - 80:8000
      - 443:8443
      - 8001:8001
      - 8002:8002
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 2s
      retries: 5
  
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    restart: always
