services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    restart: always
    container_name: node-exporter
    # network_mode: host
    pid: host
    # volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    #   - /:/rootfs:ro
    command:
      - '--web.listen-address=0.0.0.0:9100'
      # - '--path.procfs=/host/proc'
      # - '--path.rootfs=/rootfs'
      # - '--path.sysfs=/host/sys'
      # - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://127.0.0.1:9100/metrics"]
      interval: 10s
      timeout: 10s
      retries: 3