services:
  pushgateway:
    image: prom/pushgateway:${PUSH_GATEWAY_VERSION:-v1.11.1}
    container_name: pushgateway
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 9091:9091
