services:
  tempo:
    image: grafana/tempo:${TEMPO_VERSION:-latest}
    container_name: tempo
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./conf/tempo.yml:/conf/tempo.yml
      - ./tempo_data:/var/tempo
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095"   # tempo grpc
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
      - "9411:9411"   # zipkin
    command: [ "-config.file=/conf/tempo.yml" ]
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:3200/metrics"]
      interval: 10s
      timeout: 10s
      retries: 3

  memcached:
    image: memcached:${MEMCACHED_VERSION:-latest}
    container_name: memcached
    restart: always
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use
    healthcheck:
      test: ["CMD", "echo", "version", "|", "nc", "-vn", "-w", "1", "127.0.0.1", "11211"]
      interval: 10s
      timeout: 10s
      retries: 3
# mkdir -p tempo_data && chown -R 10001:10001 tempo_data
